#!/usr/bin/env python3
"""superterm test: the suite list and the suite files must agree.

`make test` runs exactly the names in Makefile.in's TESTS variable, so a suite
file which nobody added to that list is never executed. The reverse mistake is
also caught: a renamed or deleted file must not leave a stale TESTS entry.

Makefile is generated by configure. Comparing it with the template prevents a
configured checkout from silently running an older suite inventory.
"""
import glob
import os
import re
import sys


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
TEST_DIR = os.path.join(ROOT, 'test')
failed = False


def check(label, condition):
    global failed
    print(f'{label:52s}: {"OK" if condition else "FAIL"}')
    if not condition:
        failed = True


def parse_tests(path):
    """Return a makefile TESTS list in declaration order, or None."""
    try:
        with open(path, encoding='utf-8') as handle:
            lines = handle.read().splitlines()
    except OSError:
        return None
    entries = []
    collecting = False
    for line in lines:
        if not collecting:
            match = re.match(r'^TESTS\s*:?=\s*(.*)$', line)
            if match is None:
                continue
            collecting = True
            body = match.group(1)
        else:
            body = line
        more = body.endswith('\\')
        if more:
            body = body[:-1]
        entries.extend(body.split())
        if not more:
            break
    return entries if collecting else None


def duplicates(entries):
    seen = set()
    repeated = []
    for name in entries:
        if name in seen and name not in repeated:
            repeated.append(name)
        seen.add(name)
    return repeated


def main():
    template = os.path.join(ROOT, 'Makefile.in')
    generated = os.path.join(ROOT, 'Makefile')
    listed = parse_tests(template)
    check('Makefile.in declares a TESTS list', listed is not None)
    if listed is None:
        print('\nRESULT: FAIL')
        return 1

    present = sorted(os.path.basename(path) for path in
                     glob.glob(os.path.join(TEST_DIR, '*_test.py')))
    repeated = duplicates(listed)
    check('no suite is listed twice in TESTS', not repeated)
    for name in repeated:
        print(f'  duplicated in TESTS: {name}')

    missing_files = [name for name in listed if name not in present]
    check('every TESTS entry has a suite file', not missing_files)
    for name in missing_files:
        print(f'  listed in TESTS but no test/{name}')

    listed_set = set(listed)
    orphans = [name for name in present if name not in listed_set]
    check('every suite file is listed in TESTS', not orphans)
    for name in orphans:
        print(f'  test/{name} exists but no TESTS entry runs it')

    check('this suite is itself listed in TESTS',
          os.path.basename(__file__) in listed_set)

    built = parse_tests(generated)
    if built is None:
        print('generated Makefile absent; staleness check skipped')
    else:
        check('generated Makefile matches Makefile.in TESTS', built == listed)
        if built != listed:
            print('  re-run ./configure to regenerate Makefile')

    print()
    if failed:
        print('RESULT: FAIL')
        return 1
    print(f'RESULT: PASS ({len(present)} suites)')
    return 0


sys.exit(main())
