#!/usr/bin/env python3
"""superterm test: the suite list and the suite files must agree.

`make test` runs exactly the names in Makefile.in's TESTS variable, so a suite
file which nobody added to that list is never executed -- and it fails
silently, by never running at all. The reverse mistake is just as quiet until
someone reads the runner's output carefully: a renamed or deleted file leaves
a name in TESTS which the runner then reports as missing.

Makefile itself is generated by ./configure and is not tracked, so a checkout
which pulled a new Makefile.in without re-running configure keeps running the
OLD list. That has already cost this project one silently missing install path
(see the Makefile regeneration rule), so the generated list is compared with
the template's too.

This suite is deliberately static: no daemon, no PTY, no build.
"""
import glob
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
TEST_DIR = os.path.join(ROOT, 'test')
failed = False


def check(label, condition):
    global failed
    print(f'{label:52s}: {"OK" if condition else "FAIL"}')
    if not condition:
        failed = True


def parse_tests(path):
    """Return the TESTS entries of a makefile, in order, or None if absent.

    The variable is written as one assignment continued over many lines with
    trailing backslashes; the continuation ends at the first line which does
    not have one.
    """
    try:
        with open(path, encoding='utf-8') as handle:
            lines = handle.read().splitlines()
    except OSError:
        return None
    entries = []
    collecting = False
    for line in lines:
        if not collecting:
            match = re.match(r'^TESTS\s*:?=\s*(.*)$', line)
            if match is None:
                continue
            collecting = True
            body = match.group(1)
        else:
            body = line
        more = body.endswith('\\')
        if more:
            body = body[:-1]
        entries.extend(body.split())
        if not more:
            break
    if not collecting:
        return None
    return entries


def duplicates(entries):
    seen = set()
    repeated = []
    for name in entries:
        if name in seen and name not in repeated:
            repeated.append(name)
        seen.add(name)
    return repeated


def main():
    template = os.path.join(ROOT, 'Makefile.in')
    generated = os.path.join(ROOT, 'Makefile')

    listed = parse_tests(template)
    check('Makefile.in declares a TESTS list', listed is not None)
    if listed is None:
        print('\nRESULT: FAIL (1): Makefile.in declares a TESTS list')
        sys.exit(1)

    present = sorted(os.path.basename(p)
                     for p in glob.glob(os.path.join(TEST_DIR, '*_test.py')))

    repeated = duplicates(listed)
    check('no suite is listed twice in TESTS', not repeated)
    for name in repeated:
        print(f'  duplicated in TESTS: {name}')

    missing_files = [n for n in listed if n not in present]
    check('every TESTS entry has a suite file', not missing_files)
    for name in missing_files:
        print(f'  listed in TESTS but no test/{name}')

    orphans = [n for n in present if n not in set(listed)]
    check('every suite file is listed in TESTS', not orphans)
    for name in orphans:
        print(f'  test/{name} exists but no TESTS entry runs it')

    # This suite is only a guardrail if the guardrail itself runs.
    check('this suite is itself listed in TESTS',
          os.path.basename(__file__) in set(listed))

    built = parse_tests(generated)
    if built is None:
        # Running the file directly in a checkout which has not been
        # configured is legitimate; `make test` always has a Makefile.
        print('generated Makefile absent; staleness check skipped')
    else:
        check('generated Makefile matches Makefile.in TESTS',
              built == listed)
        if built != listed:
            only_built = [n for n in built if n not in set(listed)]
            only_template = [n for n in listed if n not in set(built)]
            for name in only_built:
                print(f'  stale Makefile still runs {name}')
            for name in only_template:
                print(f'  stale Makefile does not run {name}')
            print('  re-run ./configure to regenerate the Makefile')

    print()
    if failed:
        print('RESULT: FAIL')
        sys.exit(1)
    print(f'RESULT: PASS ({len(present)} suites)')
    sys.exit(0)


main()
